name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install tox tox-gh-actions
      - name: Run tests
        run: |
          tox -e py
      - name: Run tests with coverage
        run: |
          tox -e cov
      - name: Check package build
        run: |
          tox -e deploy
